# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: logicstack/gcp-sbt:0.0.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4


    environment:


    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      # run tests!
      - run: cat /dev/null | sbt test:test

#      - run:
#          name: Decode Google Cloud Credentials
#          command: echo ${GOOGLE_AUTH} | base64 -i --decode > ${HOME}/gcp-key.json
#
#      - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
#      - run: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
#      - run: gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
#      - run: gcloud --quiet components install kubectl
#      - run: gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}